version: '3'
services:
  elasticsearch:
      build:
        context: elasticsearch/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      container_name: elasticsearch
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
        - elasticsearch:/usr/share/elasticsearch/data:Z
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        node.name: elasticsearch
        ES_JAVA_OPTS: -Xms512m -Xmx512m
        # Bootstrap password.
        # Used to initialize the keystore during the initial startup of
        # Elasticsearch. Ignored on subsequent runs.
        # Use single node discovery in order to disable production mode and avoid bootstrap checks.
        # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
        discovery.type: single-node
      restart: unless-stopped
  logstash:
      build:
        context: logstash/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      container_name: logstash
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      ports:
        - 5044:5044
        - 50000:50000/tcp
        - 50000:50000/udp
        - 9600:9600
      environment:
        LS_JAVA_OPTS: -Xms256m -Xmx256m
      depends_on:
        - elasticsearch
        - kafka-1
        - kafka-2
        - kafka-3
      restart: unless-stopped
  kibana:
      build:
        context: kibana/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      container_name: kibana 
      volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      restart: unless-stopped
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper-1
    hostname: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - ./zk-data/vol1:/var/lib/zookeeper/data
      - ./zk-txn-logs/vol1:/var/lib/zookeeper/logs
  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper-2
    hostname: zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2182:2181
    volumes:
      - ./zk-data/vol2:/var/lib/zookeeper/data
      - ./zk-txn-logs/vol2:/var/lib/zookeeper/logs
  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper-3
    hostname: zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2183:2181
    volumes:
      - ./zk-data/vol3:/var/lib/zookeeper/data
      - ./zk-txn-logs/vol3:/var/lib/zookeeper/logs
  kafka-1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-1
    hostname: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./kafka-data/vol1:/var/lib/kafka/data
  kafka-2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-2
    hostname: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./kafka-data/vol2:/var/lib/kafka/data
  kafka-3:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-3
    hostname: kafka-3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./kafka-data/vol3:/var/lib/kafka/data
  akhq:
    image: tchiotludo/akhq:0.23.0
    container_name: akhq
    hostname: akhq
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    ports:
      - 8080:8080
volumes:
  elasticsearch:
